#ifndef APPSTATE_H
#define APPSTATE_H

typedef enum {
  APP_STATE_INIT,
  APP_STATE_ADD_VAULT,
  APP_STATE_ADD_VAULT_CONFIRM,
  APP_STATE_MAIN_MENU,
  APP_STATE_SYNC,
  APP_STATE_SETTINGS,
  APP_STATE_EXIT
} AppState;

#endif
